### ISSUE TITLE
Getting an error use of deprecated version

### ISSUE THREAD

**Issue by vinay375** [digreatbrian/buildozer-action#1]
Error : This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`.

But when I edit your code by replacing the line `actions/upload-artifact: v2` by
`actions/upload-artifact: v4` I was able to get the APK created.

I'm new to GitHub and YAML, but I was able to fix an issue by updating a deprecated version. However, I'm still getting warnings during debugging. Could you please explain if these warnings are a concern and how I can address them?

I'm seeing several warnings during debugging, but my application seems to be running fine and creating the APK correctly. Could you explain if this is a potential issue, and if so, how I can address it? Additionally, can you modifying your GitHub repository?

**Comment by digreatbrian** [comment]
I will soon update the deprecated versions of some packages, but using the
latest ***@***.*** its still ok

**Comment by digreatbrian** [comment]
> Error : This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`.
> 
> But when I edit your code by replacing the line `actions/upload-artifact: v2` by `actions/upload-artifact: v4` I was able to get the APK created.
> 
> I'm new to GitHub and YAML, but I was able to fix an issue by updating a deprecated version. However, I'm still getting warnings during debugging. Could you please explain if these warnings are a concern and how I can address them?
> 
> I'm seeing several warnings during debugging, but my application seems to be running fine and creating the APK correctly. Could you explain if this is a potential issue, and if so, how I can address it? Additionally, can you modifying your GitHub repository?

**Just update the the versions of actions to v4 for example upload-artifact@v4 and checkout@v4. This will ensure the action to work right away. Refer to my buildozer-action readme, it's now updated.**
